name: trakify
description: "Modified UI"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.11
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.2.0
  provider: ^5.0.0
  lottie: ^3.1.0
  http: ^1.2.1
  intl: ^0.19.0
  accordion: ^2.6.0
  connectivity: ^3.0.6
  scaled_list: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-Italic.ttf
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-Regular.ttf